services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: user_db
    ports:
      - "3305:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:

    hdshcvsajlhdvnkaehgrijk